name: Go Release Action
description: >
  Build release for go
inputs:
  target:
    description: 'Target package'
    required: true
  name:
    description: 'Output binary file name'
  divider:
    description: 'Divider for in name'
  output:
    description: 'Output dir path'
  arch:
    description: 'Target arch'
  extra-arches:
    description: 'Build all extra arches'
  extra-arches-show-default:
    description: 'Show default extra arch name'
  os:
    description: 'Target os'
  cgo:
    description: 'Enable go cgo'
  platforms:
    description: 'Specify platforms'
  ldflags:
    description: 'Add custom ldflags'
  disable-default-ldflags:
    description: 'Disable ldflags added by default'
  tread:
    description: 'How many threads to use for parallel compilation'
  compress:
    description: 'Compress the binary into the specified format of compressed file'
  mod-download-args:
    description: 'Custom args for go mod download'
runs:
  using: 'docker'
  image: 'Dockerfile'